GET http://localhost:3001/api/branches/

###

GET http://localhost:3001/api/branches/753c2c9e-f49a-4e90-8353-110bac646170

###
POST http://localhost:3001/api/branches
Content-Type: application/json

{
    "name": "สยาม",
    "address": "ไม่ทราบ",
    "telNum": "0987911234"
}

###

PATCH http://localhost:3001/api/branches/753c2c9e-f49a-4e90-8353-110bac646170
Content-Type: application/json

{
    "name": "สยาม",
    "address": "ไม่ทราบ",
    "telNum": "0987911234"
}

###
DELETE http://localhost:3001/api/branches/3de86728-700f-4456-a025-2973a79e61ff