GET http://localhost:3001/api/lockers

###

GET http://localhost:3001/api/lockers/800274fb-42db-4520-9671-127457cfae15

###
POST http://localhost:3001/api/lockers
Content-Type: application/json

{
    "branchId": "some_branch_ja",
    "userId": "some_user_ja"
}

###
DELETE http://localhost:3001/api/lockers/some-locker-id