GET http://localhost:3001/api/machines

###

GET http://localhost:3001/api/machines/3c292250-0630-4c38-a862-ee5b992489cf

###
POST http://localhost:3001/api/machines
Content-Type: application/json

{
    "branchId": "some-branch",
    "status": "working",
    "type": "20"
}

###
DELETE http://localhost:3001/api/machines/3c292250-0630-4c38-a862-ee5b992489cf