GET http://localhost:3001/api/machines

###

GET http://localhost:3001/api/machines/05d08d64-9b02-4b1e-8808-8dd41dad94eb

###
POST http://localhost:3001/api/machines
Content-Type: application/json

{
    "branchId": "some-branch",
    "status": "Not Available",
    "type": "20"
}

###
PATCH  http://localhost:3001/api/machines/05d08d64-9b02-4b1e-8808-8dd41dad94eb
Content-Type: application/json

{
    "branchId": "some-branch",
    "status": "working",
    "type": "20"
}

###
DELETE http://localhost:3001/api/machines/05d08d64-9b02-4b1e-8808-8dd41dad94eb